name: armoyu_desktop
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  armoyu_services: ^1.0.0+3
  socket_io_client: ^3.0.0
  flutter_webrtc: ^0.11.7
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.1
  flutter_background: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
